// Use crypto.randomUUID() to create unique IDs, see:
// https://nodejs.org/api/crypto.html#cryptorandomuuidoptions
const { randomUUID } = require('crypto');
// Use https://www.npmjs.com/package/content-type to create/parse Content-Type headers
const contentType = require('content-type');

// Functions for working with fragment metadata/data using our DB
const {
  readFragment,
  writeFragment,
  readFragmentData,
  writeFragmentData,
  listFragments,
  deleteFragment,
} = require('./data');

class Fragment {
  constructor({ id, ownerId, created, updated, type, size = 0 }) {
    // validation - Do not construct a fragment object if these fail
    // a fragment MUST have an owner, its type MUST be supported, and its SIZE must be a number >= 0
    if (!ownerId) throw new Error('Fragment is missing an owner');
    if (!Fragment.isSupportedType(type)) throw new Error(`Unsupported type: ${type}`);
    if (size < 0 || !(typeof size === 'number'))
      throw new Error('Size of fragment must be a an unsigned number value');

    // some properties like the id and dates can be generated by the constructor if not passed in
    this.id = !id ? randomUUID() : id; // generate an id if one is missing
    // both date fields can be generated in standardized machine-readable format if not passed into the constructor
    this.created = !created ? new Date().toISOString() : created;
    this.updated = !updated ? new Date().toISOString() : updated;

    this.type = type;
    this.ownerId = ownerId;
    this.size = size;
  }

  /**
   * Get all fragments (id or full) for the given user
   * @param {string} ownerId user's hashed email
   * @param {boolean} expand whether to expand ids to full fragments
   * @returns Promise<Array<Fragment>>
   */
  static async byUser(ownerId, expand = false) {
    const fragments = await listFragments(ownerId, expand);
    // need to determine what to return by the expand param, expand expects an array
    if (!expand) return Promise.resolve(fragments);
    // refactored this code as original expand path used [JSON.parse(fragments)] as a return
    // where fragments is an array of strings from the memory layer, this will throw
    // it now maps to rehydrate into Fragment objects instead
    else
      return Promise.resolve(
        fragments.map((fragment) => {
          if (typeof fragment === 'string') {
            const fragmentObj = JSON.parse(fragment);
            return new Fragment(fragmentObj);
          } else {
            return fragment;
          }
        })
      );
  }

  /**
   * Gets a fragment for the user by the given id.
   * @param {string} ownerId user's hashed email
   * @param {string} id fragment's id
   * @returns Promise<Fragment>
   */
  static async byId(ownerId, id) {
    // TIP: make sure you properly re-create a full Fragment instance after getting from db.
    const found = await readFragment(ownerId, id);
    if (!found) throw new Error(`Fragment "${id}" not found`);
    return Promise.resolve(new Fragment(found));
  }

  /**
   * Delete the user's fragment data and metadata for the given id
   * @param {string} ownerId user's hashed email
   * @param {string} id fragment's id
   * @returns Promise<void>
   */
  static async delete(ownerId, id) {
    // first confirm that the fragment to be deleted actually exists
    // function should be asynchronous
    const found = await readFragment(ownerId, id);
    if (!found) throw new Error('Fragment does not exist');
    await deleteFragment(ownerId, id);
    return Promise.resolve();
  }

  /**
   * Saves the current fragment (metadata) to the database
   * @returns Promise<void>
   */
  async save() {
    // first log the time when fragment was updated prior to saving
    this.updated = new Date().toISOString();
    await writeFragment(this);
    return Promise.resolve();
  }

  /**
   * Gets the fragment's data from the database
   * @returns Promise<Buffer>
   */
  getData() {
    const data = readFragmentData(this.ownerId, this.id);
    return Promise.resolve(data);
  }

  /**
   * Set's the fragment's data in the database
   * @param {Buffer} data
   * @returns Promise<void>
   */
  async setData(data) {
    // throws immediately if not given a buffer
    if (!Buffer.isBuffer(data)) throw new Error("Must be given a buffer to set fragment's data");
    // date and time should also be updated as the fragment is modified
    this.updated = new Date(Date.now()).toISOString();
    // size of fragment updates to reflect new data
    this.size = data.length; // should be LENGTH not size
    // TIP: make sure you update the metadata whenever you change the data, so they match
    await writeFragmentData(this.ownerId, this.id, data);
    await writeFragment(this);
    return Promise.resolve();
  }

  /**
   * Returns the mime type (e.g., without encoding) for the fragment's type:
   * "text/html; charset=utf-8" -> "text/html"
   * @returns {string} fragment's mime type (without encoding)
   */
  get mimeType() {
    const { type } = contentType.parse(this.type);
    return type;
  }

  /**
   * Returns true if this fragment is a text/* mime type
   * @returns {boolean} true if fragment's type is text/*
   */
  get isText() {
    return this.mimeType.startsWith('text/');
  }

  /**
   * Returns the formats into which this fragment type can be converted
   * @returns {Array<string>} list of supported mime types
   */
  get formats() {
    return [this.mimeType];
  }

  /**
   * Returns true if we know how to work with this content type
   * @param {string} value a Content-Type value (e.g., 'text/plain' or 'text/plain: charset=utf-8')
   * @returns {boolean} true if we support this Content-Type (i.e., type/subtype)
   */
  static isSupportedType(value) {
    const supported = [
      'text/plain',
      'text/plain; charset=utf-8',
      'text/markdown',
      'text/html',
      'text/csv',
      'application/json',
      'application/yaml',
      'image/png',
      'image/jpeg',
      'image/webp',
    ];
    return supported.includes(value);
  }
}

module.exports.Fragment = Fragment;
